### PR TITLE
Adding colors to filter

### PR DESCRIPTION
**Pull request by emilyridge**

### CODE REVIEW

**Comment by Gabrieldowen** [comment]
can you give a short description on how this coloring works?

**Comment by Gabrieldowen** [comment]
also clicking on the notam displays only opens up the top one

**Comment by emilyridge** [comment]
Sorry this branch was not ready to be merged into main, David asked me to pr what I had for him to work on. But thank you for the notes, I will work on those. And the documentation for how the coloring works is in the google drive in the ColorNOTAMs file.

**Comment by Gabrieldowen** [comment]
He was able to branch off your branch to make the changes he wanted. You can double check with him but I think this can be closed

**Pull request closed without merging**
