### PR TITLE
Add map and parellize API calls

### PR DESCRIPTION
**Pull request by Gabrieldowen**
Screenshot 2024-04-19 at 7 49 20 PM

There are lots of conflicts so I wanted to make a PR so it's easier to read. With lots of changes I will need help from @DavidRamirezz to figure out how to connect them. I did try resolving them on my own but couldn't figure it out. Please let me know what you think of the map visually and if you have any suggestions.

### CODE REVIEW

**Comment by JmzCS50** [comment]
So i tried to resolve the conflicts and broke a lot of stuff. I reverted my commit so it should be ok now, but we do need to get together and resolve them because there is a lot to review and most of it was done by different people.

**Comment by DavidRamirezz** [comment]
From (what I believe) Jacob's effort to resolve the conflicts, the code was updated to reflect the main branch from before rankingComplete was merged in. So I have gone in and got everything working again. The code should work and is up to date with main. The only issue currently is when applying filters and or rank, it removes the map since it is not currently being added with the new notam list returned from applying the filtering.

**Comment by Gabrieldowen** [comment]
everything seems to work. I removed all those print statements but if nobody else finds anything it should be good

**Review by JmzCS50 — APPROVED** [review]
works, only thing is rerendering the map after filtering, could be a future fix.

**Review by okie-creator — APPROVED** [review]

**Pull request merged**
